### ISSUE TITLE
Request: a new 1.x gem version

### ISSUE THREAD

**Issue by konklone** [benbalter/site-inspector#38]
I have substantial downstream work tied to the work I did off the 1.x branch in March. I'm trying to update my downstream work to the 2.0 gem. However, this will take a bit of time, as 2.0 is (appropriately) not fully backwards-compatible in CLI or data schema to the 1.x branch.

My downstream work is tied to the last version of site-inspector I contributed to, which is currently in the branch `erics-mode`. My request is to turn this branch into a tag and release as 1.0.2. It is backwards-compatible with 1.0.1, and would allow me to at least codify my downstream work's dependencies, and to be able to compare them to 2.0 in a more clearly defined way as I transition my work.

**Comment by benbalter** [comment]
Sure thing. Get [v1.0.2](https://github.com/benbalter/site-inspector/releases/tag/v1.0.2) while it's hot, available in a GitHub or Rubygems.org near you.

> and to be able to compare them to 2.0 in a more clearly defined way as I transition my work.

Please. I was hoping you could provide some feedback on the 2.0.x changes, as there are a few tests still missing, as I didn't know your intention in the original branch.

**Comment by konklone** [comment]
> Please. I was hoping you could provide some feedback on the 2.0.x changes, as there are a few tests still missing, as I didn't know your intention in the original branch.

Very much my intent!

**Comment by konklone** [comment]
And thank you!
