### ISSUE TITLE
How to handle domains that resolve to 127.0.0.1?

### ISSUE THREAD

**Issue by konklone** [benbalter/site-inspector#50]
Here's a public domain that resolves to `127.0.0.1`: `localhost.lbl.gov`.

When `site-inspector` is run on this domain, it's completely non-deterministic, depending on where it's run. In fact, there really _aren't_ any objective **facts** about this domain to be had, except that it resolves to `127.0.0.1`. Such a domain is a hollow mirror that shows the viewer a glimpse of itself.

Given that, rather than give potentially confusing or misleading readings about the domain (it's not currently easily discoverable unless something looks subjectively amiss in the results), I think `site-inspector` should treat this as a unique kind of failure condition.

**Comment by benbalter** [comment]
> Such a domain is a hollow mirror that shows the viewer a glimpse of itself.

That's deep.

> I think site-inspector should treat this as a unique kind of failure condition.

My initial instinct says it should raise some sort of `SiteInspector::Localhost` error, but given how things are often used in batch, may not be the best approach. Perhaps fail early and return an error in the JSON?

**Comment by konklone** [comment]
> Perhaps fail early and return an error in the JSON?

That sounds good to me. As if it's unreachable, but a distinct error message that allows clients to disambiguate the two conditions. :+1:
