### ISSUE TITLE
support question: check for mixed mode warnings

### ISSUE THREAD

**Issue by joelcollinsdc** [benbalter/site-inspector#75]
I'm somewhat suprised that checks for mixed mode content warnings are not bundled with this app.  Is it there already and I missing it?  Or, is there a reason its been left out?  

Is this something that would be valuable to add generically (fork/pull) or would you recommend just adding it as a custom check?

I suppose to do this check properly you would need a real browser emulator, but a simple test for http iframes, js, etc may be sufficient.

**Comment by benbalter** [comment]
I'd suspect you'd need to spin up a headless browser, which would also require downloading and traversing all the assets/dependencies.

@konklone any thoughts on a smarter way to do this?

**Comment by konklone** [comment]
Hey @joelcollinsdc, I've been using https://github.com/bramus/mixed-content-scan to scan sites for mixed content. It's not something we've integrated into pulse.cio.gov, though it's easy to imagine doing so.

It doesn't involve a headless browser, which gives it the limitation that it only detects statically defined code references to mixed content. Requests generated by JavaScript code won't get caught. But it's really pretty good, and simple. I helped add code to the library to enable JSON output too, if you want to feed it into another system.

**Comment by joelcollinsdc** [comment]
Lots of options.  Thanks all.

**Comment by joelcollinsdc** [comment]
Sorry guys,

**Comment by konklone** [comment]
Pinging the thread to note the subsequently added comments, and to defer to @benbalter on integration.

**Comment by joelcollinsdc** [comment]
Sorry I'm a mess right now.  Its working, I just wasn't calling the check correctly... I was using endpoint.mentions? instead of endpoint.mention.mentions?

**Comment by joelcollinsdc** [comment]
This is what I came up with in case anyone has a similar request.  probably not ready for actual inclusion yet, its pretty rough.

https://gist.github.com/joelcollinsdc/1dec34f69e2b028f1f5f

**Comment by konklone** [comment]
I left a couple notes at the bottom -- very interested to see how well it works for you!
