### ISSUE TITLE
support troubleshooting inconsistent results when run in a script

### ISSUE THREAD

**Issue by joelcollinsdc** [benbalter/site-inspector#81]
I'm trying to figure out why we are consistently seeing a handul of https? == false results when we run this script in a batch (500 sites total).  Restarting our ruby app and testing the same sites again causes https? to be true.  

* This normally happens to sites on a particular server or servers, so Its likely related to some kind of timeout or other server/network issue
* I'm seeing similar (but different) results when using a proxy, We get about 1-2% false positives (also on a server, but perplexingly a different server than when not using the proxy)

I was going to put some kind of delay or reduce the currency and see if that helped.  Also due to memoization the false positives are saved... not sure if there is a strategy to get around that.

**Comment by joelcollinsdc** [comment]
I think I know whats going on, but running with debug on, i see

App 10921 stdout: About to connect() to [domain] port 443 (#0)
App 10921 stdout:   Trying [ip]...
App 10921 stdout: Closing connection #12
App 10921 stdout: Connection (#12) was killed to make room (holds 16)

Also, googling "connection was killed to make room" is ... interesting....

I'm trying to run this with typhoeus_options = { forbid_reuse: true }..

Although, since I'm running into these issues, this seems like I'm doing something wrong.  Shoudl I not be using this for this use case?

**Comment by konklone** [comment]
It looks like `connection ... was killed to make room` is a cURL thing, not a Typhoeus thing:

http://blog.gmane.org/gmane.comp.web.curl.php/month=20081001
http://curl.haxx.se/mail/lib-2006-09/0130.html
http://tekfacts.com/ow-do-pull-from-a-it-repository-through-an-proxy/

I'm not sure if the `curl` CLI client shares state between independent requests, or if it means something else entirely.

> This normally happens to sites on a particular server or servers, so Its likely related to some kind of timeout or other server/network issue

I observe a number of "troublemakers" in the .gov space that exhibit common fluctuations week-to-week, where they appear go on and off. I think it relates to them either having intermittent outages, or taking long enough to time the client out. There's also sometimes issues with us making cURL requests from an EC2 instance and how requests from Amazon get handled by enterprise network edges.

Entropy is high out there. :/

**Comment by joelcollinsdc** [comment]
Thanks @konklone, I think the forbid_reuse thing worked for me, I can see the connections getting killed instead of re-used...  I've also had to bump up timeouts to 30 seconds (!!!) to cut down on errors.

**Comment by konklone** [comment]
Sadly, 30s is the minimum timeout I need to apply for "government websites" as well.
