### ISSUE TITLE
Installation Information

### ISSUE THREAD

**Issue by mgifford** [benbalter/site-inspector#85]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

I'm having trouble understanding this, but I suspect it's my very limited understanding of Ruby.  It would be useful thought to know general install instructions though. 

What version of Ruby is this developed for? I'm using ruby 2.6.3p62 which isn't the latest (just what Mac's run with). 

This seems to work:
`$ bundle install `

From there I think I should be able to run:
  `$ ./bin/site-inspector inspect whitehouse.gov -a`

But that just gives me this error:

```
Traceback (most recent call last):
	5: from ./bin/site-inspector:8:in `<main>'
	4: from ./bin/site-inspector:8:in `require_relative'
	3: from /Users/mgifford/Documents/GitHub/site-inspector/lib/site-inspector.rb:75:in `<top (required)>'
	2: from /Users/mgifford/Documents/GitHub/site-inspector/lib/site-inspector.rb:35:in `cache'
	1: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- site-inspector/cache (LoadError)
```

I've searched around to try to find ways around this but no luck.... 

### Describe the solution you'd like

I'd like to have basic install instructions.

**Comment by benbalter** [comment]
Try `bundle exec ./bin/site-inspector inspect whitehouse.gov -a`? Ruby can be a bit finicky with dependencies and it looks like site inspector's libraries aren't in ruby's load path when it's initialized.

**Comment by mgifford** [comment]
That seemed to work in my Linux environment. Still working on getting it to work on a Mac, but this now is clearly not an issue with your scripts. Thanks @benbalter - appreciate the pointer.

**Comment by mgifford** [comment]
Just wanting to add that it is also useful for me with 2021-analysis-of-federal-dotgov-domains is that it is useful to prepend `bundle exec`.  Without it I get:

```
$ ./script/crawl 
Traceback (most recent call last):
        2: from ./script/crawl:6:in `<main>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- site-inspector (LoadError)
```

But it is working like a charm with the `bundle exec`.  Thanks.
